"""
ai_responder.py - Compose Reddit-ready replies using the LLM layer.
"""

import praw.models

from config import MODEL
from llm import ai_answer


def build_reply_text(trigger_comment: praw.models.Comment) -> str:
    """Generate an AI answer and append model attribution for Reddit replies."""
    answer = ai_answer(trigger_comment)
    return f"{answer}\n\n---\n\n*^(This comment was generated by {MODEL})*"
