#!/usr/bin/env python3
"""
main.py – Entry point for HelperBot.

Validates configuration, starts the stats-logging thread, and runs the
main Reddit comment-stream loop with retry logic and graceful shutdown.
"""

import signal
import sys
import threading
import time
import logging

from config import (
    MODEL,
    REDDIT_RATE_LIMIT_SEC,
    SUBS,
    TRIGGER,
    logger,
    reddit,
    validate_env,
)
from llm import ai_answer

# ── Stats tracking ───────────────────────────────────────────────────────
stats_lock = threading.Lock()
comments_read = 0
comments_written = 0

# Graceful-shutdown flag
_shutdown = threading.Event()


def log_status() -> None:
    """Log stats every 60 seconds until shutdown is requested."""
    while not _shutdown.is_set():
        with stats_lock:
            cr = comments_read
            cw = comments_written
        logger.info("Comments read: %d, Comments written: %d", cr, cw)
        _shutdown.wait(60)


# ── Signal handling ──────────────────────────────────────────────────────


def _handle_signal(signum: int, _frame: object) -> None:
    sig_name = signal.Signals(signum).name
    logger.info("Received %s – shutting down gracefully...", sig_name)
    _shutdown.set()


signal.signal(signal.SIGINT, _handle_signal)
signal.signal(signal.SIGTERM, _handle_signal)


# ── Reddit stream with retry ────────────────────────────────────────────
MAX_STREAM_RETRIES = 5
STREAM_RETRY_BACKOFF = [10, 30, 60, 120, 300]  # seconds


def _reply_with_retry(comment: object, text: str, retries: int = 3) -> None:
    """Post a reply, retrying on transient Reddit API failures."""
    for attempt in range(retries):
        try:
            comment.reply(text)  # type: ignore[union-attr]
            return
        except Exception as exc:
            if attempt < retries - 1:
                wait = 2 ** (attempt + 1)
                logger.warning(
                    "comment.reply() failed (attempt %d/%d): %s – retrying in %ds",
                    attempt + 1,
                    retries,
                    exc,
                    wait,
                )
                time.sleep(wait)
            else:
                raise


# ── Main loop ────────────────────────────────────────────────────────────


def main() -> None:
    validate_env()
    logger.info("helperbot is live")

    global comments_read, comments_written

    status_thread = threading.Thread(target=log_status, daemon=True)
    status_thread.start()

    stream_failures = 0

    while not _shutdown.is_set():
        try:
            for comment in reddit.subreddit("+".join(SUBS)).stream.comments(
                skip_existing=True
            ):
                if _shutdown.is_set():
                    break

                with stats_lock:
                    comments_read += 1

                if not TRIGGER.match(comment.body):
                    continue

                logger.info(
                    "Trigger detected in r/%s | %s",
                    comment.subreddit.display_name,
                    comment.id,
                )
                logger.info("Trigger comment: %r", comment.body.strip())

                try:
                    reply_text = (
                        ai_answer(comment)
                        + "\n\n---\n\n*^(This comment was generated by "
                        + MODEL
                        + ")*"
                    )
                    _reply_with_retry(comment, reply_text)
                    with stats_lock:
                        comments_written += 1
                    logger.info("Replied successfully")
                except Exception as exc:
                    logger.error("Failed to generate/post reply: %s", exc)

                time.sleep(REDDIT_RATE_LIMIT_SEC)

            # Stream ended normally (shouldn't happen)
            stream_failures = 0

        except Exception as exc:
            if _shutdown.is_set():
                break
            backoff = STREAM_RETRY_BACKOFF[
                min(stream_failures, len(STREAM_RETRY_BACKOFF) - 1)
            ]
            logger.error(
                "Comment stream error (attempt %d): %s – retrying in %ds",
                stream_failures + 1,
                exc,
                backoff,
            )
            stream_failures += 1
            if stream_failures > MAX_STREAM_RETRIES:
                logger.critical(
                    "Exceeded max stream retries (%d). Exiting.", MAX_STREAM_RETRIES
                )
                sys.exit(1)
            time.sleep(backoff)

    logger.info("Shutdown complete.")


if __name__ == "__main__":
    main()
