name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} <<'EOF'
          cd /home/peter/apps/reddit-helperbot
          git pull origin main
          docker stop reddit-helperbot || true
          docker rm reddit-helperbot || true
          docker build -t reddit-helperbot .
          docker run -d --restart=always --name reddit-helperbot reddit-helperbot
          EOF
